language: python
services: docker
git:
  depth: 5
matrix:
  include:
  - python: 2.7
  - python: 3.6
  - env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - os: osx
    language: generic
    env: PYENV=py27
  - os: osx
    language: generic
    env: PYENV=py36
before_install:
- travis_retry bash <(curl -s https://raw.githubusercontent.com/limix/travis-tools/master/get-travis-tools.sh)
- which pip
- which python
- echo $PYTHONPATH
- pip install liknorm
- find /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages
- travis_retry travis/before-install.sh
install:
- travis_retry travis/install.sh
script:
- travis_retry travis/script.sh
after_success:
- travis_retry travis/after-success.sh
notifications:
  email:
    recipients:
      - danilo.horta@gmail.com
    on_success: change
    on_failure: always
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  user: dhorta
  password:
    secure: kJx9NqIGL2zSc5+R6Ktqssv6/n1whi6sB0FQKK+/SE/tNl3OnmqJ9lYF8/J2IMt1Uhz44gIWJl0uzPWUCQqghT7pSqUy1MN1yhlkxh4W0thZMc6eXEWbOHrPp0pC2GvpgDy0xys5+OzI1v1khpZMt0KP1vuSb/Z5G+wkDxqCU/ep2JObI/3GgbkNx/3I0SBKDvYmvNgq39HMwidx3YW+LgWsWsEYAJBFmKM58UkT+EXfcWOxy2K0Aqt6uULEZEYk3y39nJxOTaLGUx19wfQNQQO0ugOX6mGHKRK34mb+DFfV2VOMrV093dSyelsHq5pT9d628L+l9TEg0WlXgt3ABOagB6dBV66CNRCD29SuOBbQebKNjBV0OLX8xB0BcEG9n/H0GWkOSxP79wL1oB3kIJB6pasZ0rCvgfddyjFr900+okdXCqiXH4bPfvOMRsSGF9gNqERWbGlqs2lAnUZlkdt2l+1w2KSRTDvogGaXT1cC/T71ttnPkATJN+SagPEPGTOUYFgLGsdYY9/j0zrSXzbXujR2lTG0zAsvZ4lhGujc/EBdAZ4/di+wZfOM+EyU6pefzYVZg4q2yDkdr1GxwAPN5BB4VHRLsw2IgEyYedWHYS66vvNZ7KuuF336Y3Sp6lDXz0mL6AYixOBh46YolxlGqhcGFkpkE7I0WBQD2c4=
  on:
    tags: true
    repo: limix/glimix-core
    branch: master
env:
  global:
    - secure: A0SPfnMMsWf0eoEnOfrCd6yRrdGseBz1dKCN1O7AkzUG6LguFXru2dyHKiSdjL3oKuSzXH1IXZUbZqSQ9Y9DHscsYhuNWYRTRNfhw5pp+CMhOzAlqiNTGQZ3OSC/v9jq2YEfImgT7/kYfYT3w/eEVfg5GrxloRAlKk0fvihhseOx9NsuUFEPMWSo+J75kXcCXMhdV8gSrVtBVvhCtUiUkT4uQLlWwfofWc7ROtarPv6pg/MfT/f/13Ts9/V+lraubVy8RWd+OP0e7fjb6jVRP9IwsZ3yd2lKMXscoKNG1Mc9Sq18MmLuUJeHG20wqjpHoYlKEAvVAgmk40w/zLFOuCZyoPQQ3Zl/eluGxGdHy1UUyLmrVB2Mj1cHkLbU8TCyrTmn4B/yb58H4gzyCdn7Ho/HrvRr7B7yfySqIoW5sojf0n4VqzGaxlDFP7MpZt6jWRUwaU3Bs+rcGeRGMek5ByBgO3cKVUlGOAkdts7kY6JeFNp2WHMfzeM1jtnP1LGSHmjy6D9pLt1NH15pwD+b0ujc69StuQ6iGlZI6c1zX7gypFK0/c3Fiux8WbHZGt6pvnzliYQRZ5FPQa+VpiUb8ev6xKHxR6zKPo3cIyxJU/tpYrorZt8iyuZarRV5fVpmMz/W2tgslVnlxaAzkAASfF3GE2J42PEpNJpEBDtB8vo=
    - LIKNORM=true
    - HCEPHES=true
