language: python
sudo: required
dist: trusty
git:
  depth: 5
matrix:
  include:
  - python: 2.7
    compiler: clang-3.8
    env: NUMBA="true" LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8" "PATH=~/bin:$PATH"
  - python: 3.5
    compiler: clang-3.8
    env: NUMBA="true" LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8" "PATH=~/bin:$PATH"
  - python: 3.6
    compiler: clang-3.8
    env: NUMBA="true" LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8" "PATH=~/bin:$PATH"
before_install:
- travis_retry travis/install_clang38.sh;
- travis_retry travis/install_llvmlite.sh;
- travis_retry travis/install_pandoc.sh
- travis_retry travis/install_liknorm.sh
script:
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`[numba] -vvv;
- pushd /
- python -c "import sys; import limix_inference; sys.exit(limix_inference.test())"
- popd
notifications:
  email: false
