language: python
sudo: false
python: 3.6
env:
  - PKG_NAME=glimix_core
addons:
  apt:
    packages:
      - pandoc
install:
- bash <(curl -fsSL https://raw.githubusercontent.com/limix/liknorm/master/install)
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
      - danilo.horta@gmail.com
    on_success: never
    on_failure: always
