language: python
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - ccache
cache:
  directories:
    - $HOME/.ccache
matrix:
  include:
  - os: linux
    python: '2.7'
  - os: linux
    python: '3.4'
  - os: linux
    python: '3.5'
before_script:
  - sudo add-apt-repository -y 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main' || true
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add - || true
  - sudo apt-get install -qq -y clang-3.8 zlib1g-dev libbz2-dev || true
  - if [ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]; then pip install enum34; fi
  - sudo apt-get update -y || true
  - export CXX="clang++-3.8"
  - git clone https://github.com/numba/llvmlite.git --depth 1
  - pushd llvmlite
  - python setup.py install
  - popd
script:
  - export CXX="clang++-3.8"
  - python setup.py sdist
  - pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
  - pushd /
  - python -c "import limix_inference; limix_inference.test()"
  - popd
notifications:
  email: false
