language: python
sudo: required
dist: trusty
compiler: clang-3.8
env: LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8" LD_LIBRARY_PATH="$HOME/liknorm/lib:$LD_LIBRARY_PATH"
python:
- 2.5
- 3.5
git:
  depth: 5
before_install:
- sudo add-apt-repository -y 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8
  main' || true
- wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add - || true
- sudo apt-get update -y || true
- sudo apt-get install -qq -y clang-3.8 zlib1g-dev libbz2-dev || true
install:
- mkdir $HOME/liknorm
- wget https://github.com/glimix/liknorm/archive/v1.2.0.tar.gz
- tar xzf v1.2.0.tar.gz && mkdir liknorm-1.2.0/build
- pushd liknorm-1.2.0/build
- cmake -DCMAKE_INSTALL_PREFIX=$HOME/liknorm .. && make && make install
- popd && rm -rf liknorm-1.2.0/ && rm v1.2.0.tar.gz
script:
- export C_INCLUDE_PATH=$HOME/liknorm/include:$C_INCLUDE_PATH
- export CPLUS_INCLUDE_PATH=$HOME/liknorm/include:$CPLUS_INCLUDE_PATH
- if [ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]; then pip install enum34; fi
- pip install pypandoc
- git clone https://github.com/numba/llvmlite.git --depth 1
- pushd llvmlite
- CXX_FLTO_FLAGS= LD_FLTO_FLAGS= python setup.py install
- popd
- python -c "from pypandoc import download_pandoc as dp; dp(targetfolder='~/bin/');"
- export PATH=~/bin:$PATH
- "~/bin/pandoc -v"
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import limix_inference; limix_inference.test()"
- popd
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: r2RcXyoga4bMjmaj7CgOKMXtOAh2Azaz/Jtesk1/Kn28satpVyd1UWeeqOcK93m1TE4AGrQXjoEaxu0XqzNtGJ1m98eUybEvJy0MirxgQ30FfxUZVYVaa68/IbOWMz8UO9MSPVWYRwZoPnywsD4WHmF8s8rs9LT2p+kQQFaHm4uaSWyuW426DAluBaGwtSziV/q3fOOIiFOngAlztjA2cMvMpvcSa/l/mJlk+BvDVGC8yPrAj2lH30BAo4pxcbmxaOgtCTejC743zVRVyvyEbjicuTRIH46pztlzjIxR/Z+1pddzQQ/Ev7mJCUaNFwSycvJWWRmQvCVz7XJ9A+RuQxlLjs0tDeFV1HZ+3gJO2osASi/RJ9MidnmJrpCuMnDabGmmt5Rr00ubbObh5eHUCsRwirKexPfZLpyw6KqxU5JNt3e45JiWcqvFwR994916Ms9ydKDQ4h4FWc93U6SLei7vvweTiEeCKETGXaID4PCTQVC3AWJgZpIrfgA+SgW5cIOgLi38ECdc5lkPJ0wg6fM/YyLFgfJWS7Zlq68t5CPCBq7WrOw0fS/zOz0mnvO/9mjygY1F0RlZugQcWGhHj2B6nxTnV01ljKMlRCK7Rsfqss8F3rRMmw7p2OjgPF0ua/38nErWup/2HU3Mhm4Aj4d3fXYQBMYVNVeSLyfdx9A=
  on:
    distributions: sdist
    repo: glimix/limix-inference
    branch: liknorm
