language: python
sudo: required
dist: trusty
python:
  - 2.7
  - 3.5
git:
  depth: 5
before_install:
- sudo add-apt-repository -y 'deb http://llvm.org/apt/trusty/
  llvm-toolchain-trusty-3.8 main'
- wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
- sudo apt-get update -y
- sudo apt-get install -qq -y clang-3.8 zlib1g-dev libbz2-dev
- if [ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]; then pip install enum34 -q; fi
- LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8" CXX_FLTO_FLAGS= LD_FLTO_FLAGS= pip install llvmlite -q
install:
- wget https://github.com/glimix/liknorm/archive/v1.2.0.tar.gz
- tar xzf v1.2.0.tar.gz && mkdir liknorm-1.2.0/build
- pushd liknorm-1.2.0/build
- export LDFLAGS="-L$(python-config --prefix)/lib"
- cmake -DCMAKE_INSTALL_PREFIX=`python-config --prefix` .. && make && sudo make install
- popd && rm -rf liknorm-1.2.0/ && rm v1.2.0.tar.gz
script:
- pip install pypandoc -q
- python -c "from pypandoc import download_pandoc as dp; dp(targetfolder='~/bin/');"
- export PATH=~/bin:$PATH
- export LDFLAGS="-L$(python-config --prefix)/lib"
- export CFLAGS="$(python-config --cflags) -I$(python-config --prefix)/include"
- echo $LDFLAGS
- echo $CFLAGS
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1` -q
- pushd /
- python -c "import limix_inference; limix_inference.test()"
- popd
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  on:
    distributions: sdist
    repo: glimix/limix-inference
    branch: master
