channels:
- conda-forge
- defaults
dependencies:
- hcephes=0.2.3=1
- liknorm=1.3.11=0
- libffi=3.2.1
- ncurses=6.0
- numpy=1.13.1
- pandas=0.20.3
- pip=9.0.1
- python=3.5.4
- python-dateutil=2.6.1
- pytz=2017.2
- readline=7.0
- scipy=0.19.1
- setuptools=36.5.0
- six=1.10.0
- sqlite=3.20.1
- tk=8.6.7
- wheel=0.29.0
- xz=5.2.3
- zlib=1.2.11
- pip:
  - apipkg==1.4
  - brent-search==1.0.29
  - cachetools==2.0.1
  - dask==0.15.3
  - execnet==1.4.1
  - ndarray-listener==1.0.26
  - numpy-sugar==1.1.2
  - optimix==1.2.21
  - pep8==1.7.0
  - py==1.4.34
  - pytest==3.2.2
  - pytest-cache==1.0
  - pytest-pep8==1.0.6
  - pytest-sugar==0.9.0
  - scipy-sugar==1.0.4
  - sphinx-rtd-theme==0.2.4
  - termcolor==1.1.0
  - toolz==0.8.2
  - tqdm==4.18.0
