name: root
channels:
- 'defaults'
dependencies:
- cffi=1.8.3=py27_0
- enum34=1.1.6=py27_0
- libffi=3.2.1=0
- libgfortran=3.0.0=1
- nomkl=1.0=0
- numpy=1.11.2=py27_nomkl_0
- openblas=0.2.14=4
- openssl=1.0.2h=1
- pip=8.1.2=py27_0
- pycosat=0.6.1=py27_1
- pycparser=2.17=py27_0
- pycrypto=2.6.1=py27_4
- python=2.7.12=1
- pyyaml=3.11=py27_4
- readline=6.2=2
- requests=2.10.0=py27_0
- ruamel_yaml=0.11.14=py27_0
- scipy=0.18.1=np111py27_nomkl_0
- setuptools=23.0.0=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - ruamel-yaml-==VERSION
